dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE playtogetherdb;'
  - mysql -e 'CREATE USER "user" IDENTIFIED BY "password";'
  - mysql -e 'GRANT USAGE ON *.* TO "user"@"%" IDENTIFIED BY "password";'
  - mysql -e 'GRANT ALL privileges ON `playtogetherdb`.* TO "user"@"%";'
  - mysql -e 'FLUSH PRIVILEGES;'
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml
